services:
  webserver:
    env_file:
      - .env.compose
    build: 
      context: .
      dockerfile: Dockerfiles/server.Dockerfile
    ports:
      - "8080:8081"
  postgresdb:
    env_file:
      - .env.compose
    image: postgres:16-bookworm
    ports:
      - "5455:5432"